name: my-github-status
on:
  workflow_dispatch:
  schedule:
    - cron: "1 1 1 1 1"
  push:
    branches:
      - main

env:
  GITHUB_NAME: yanggangtony
  GITHUB_EMAIL: yanggangtony@163.com

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: My GitHub Status
        uses: yanggangtony/yanggangtony@main
        with:
          GH_USERNAME: yanggangtony
      - name: Push README
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'docs: update readme.md'
          git push
